apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-default
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    priority: 1
    services:
    - name: app3-service
      port: 80
