Vagrant.configure("2") do |config|
  config.vm.define "amidoyanS" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "amidoyanS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install.sh"
  end
end